### ISSUE TITLE
[BUG] Colors not converting RGB values

### ISSUE THREAD

**Issue by Sneakpeakcss** [Flow-Launcher/Flow.Launcher.Plugin.Color#3]
_Flow.Launcher = v1.9.3
Colors = v2.0.1_

Colors converts HEX values properly even to RGB

![1](https://user-images.githubusercontent.com/77424331/161385533-5052e04d-e1ec-408a-b743-0b6162f9985a.png)
but using **any** RGB value throws a windows notification error from Flow.Launcher:

![2](https://user-images.githubusercontent.com/77424331/161385624-a74dac9f-5bd9-4269-80a3-3de23c2f2775.png)
![3](https://user-images.githubusercontent.com/77424331/161385630-dc4da804-4085-4ef0-b16e-dde86031cd77.png)

Here's a full Flow.Launcher log after going through listed examples ( #d948a7 -> 217,72,167 -> 99,197,34;(39,0,152) -> 255,255,255 )
https://pastebin.com/N513Ya9y

I'm not sure if this is any clue, but the listed path (_D:/a/Flow.Launcher.Plugin.Color/Flow.Launcher.Plugin.Color/_) in every error doesn't even exist on my system and everything is installed in default location (_C:\Users\\%userprofile%\AppData\Roaming\FlowLauncher\Plugins\Colors-2.0.1_)

**Comment by jjw24** [comment]
Hey I can not replicate the issue. 

What's your Windows version?

Are you using any non-English keyboard input?

**Comment by Sneakpeakcss** [comment]
@jjw24 

Win10 Pro 21H2 19044.1415

And it looks like that keyboard input idea was almost on point… 
Since the beginning my system was running in Polish, so after installing  _**English (United States)**_ package and restarting my pc, Colors works properly:

![Untitled](https://user-images.githubusercontent.com/77424331/161453838-5acc138c-c6cc-46ac-824c-d73a18a7852b.png)

And after some testing it turns out that the only option responsible for all of this is Regional Format:

![image](https://user-images.githubusercontent.com/77424331/161454194-5227e638-b54c-466d-b5be-b6bbe253d215.png)

And at first i thought that it might have something to do with Decimal separators in [different countries](https://en.wikipedia.org/wiki/Decimal_separator#Usage_worldwide), but even after changing it to **English (Germany)** Colors still works without a problem, so it looks like if it's changed to something that isn't English it starts to break.

Also, switching back to Polish and searching for values that were already cached in **_CachedImages_** works without a problem for those values.

**Comment by kubalav** [comment]
Is there any workaround to make it work with a non-English keyboard?

**Comment by jjw24** [comment]
Not that I am aware of, admittedly I haven't had time to properly look at fixing this. Do you have a workaround by any chance @Sneakpeakcss?

**Comment by Sneakpeakcss** [comment]
> Not that I am aware of, admittedly I haven't had time to properly look at fixing this. Do you have a workaround by any chance @Sneakpeakcss?

Other than permanently changing that option i never managed to find anything else, _unless we consider using ShareX's "screen color picker" as a (very bad) workaround_, but at that point you could use a dedicated 3rd party software to do the same thing as the flow plugin.

**Comment by AlesRFK** [comment]
@Sneakpeakcss yea that is how I do it - ShareX D:

**Comment by jjw24** [comment]
Hi all, flow has introduced the option in Settings to always start typing in English, this will change your IME temporarily to English when typing in the search window. Please test if this solves the problem.

**Comment by kubalav** [comment]
> Hi all, flow has introduced the option in Settings to always start typing in English, this will change your IME temporarily to English when typing in the search window. Please test if this solves the problem.

No, the problem still persists.

**Comment by Sneakpeakcss** [comment]
Yea, turning on "_Always Start Typing in English Mode_" didn't help.
```
08:21:18.9947+01:00 - ERROR - Query.Query - Colors plugin failed to convert user's input
EXCEPTION OCCURS: System.ArgumentException: 213,123,1 is not a valid value for Int32. (Parameter 'htmlColor')
 ---> System.ArgumentException: 213,123,1 is not a valid value for Int32.
 ---> System.FormatException: Input string was not in a correct format.
   at void Number.ThrowOverflowOrFormatException(ParsingStatus status, TypeCode type)
   at int int.Parse(string s, NumberStyles style, IFormatProvider provider)
   at int System.Drawing.ColorConverterCommon.IntFromString(string text, CultureInfo culture)
   --- End of inner exception stack trace ---
   at int System.Drawing.ColorConverterCommon.IntFromString(string text, CultureInfo culture)
   at Color System.Drawing.ColorConverterCommon.ConvertFromString(string strValue, CultureInfo culture)
   at Color System.Drawing.ColorTranslator.FromHtml(string htmlColor)
   --- End of inner exception stack trace ---
   at Color System.Drawing.ColorTranslator.FromHtml(string htmlColor)
   at string Flow.Launcher.Plugin.Color.ColorsPlugin.CreateCacheImage(string name) in D:/a/Flow.Launcher.Plugin.Color/Flow.Launcher.Plugin.Color/Main.cs:line 158
   at List<Result> Flow.Launcher.Plugin.Color.ColorsPlugin.Query(Query query) in D:/a/Flow.Launcher.Plugin.Color/Flow.Launcher.Plugin.Color/Ma
```

**Comment by Sneakpeakcss** [comment]
This might be an issue with `Flow Launcher` itself because there are also problems with `General Converter` plugin when certain `Regional Formats` are selected. 
I came back to this out of curiosity since github workflows allowed me to be super lazy and spare me from setting up VS to compile anything, so i've checked the "decimal separators" idea again:

<details><summary>Results</summary>

> Polish - Poland Regional format (Failed ❌):
> 
> INFO  - ColorsPlugin.Init - Decimal Separator: `,`
> INFO  - ColorsPlugin.Init - Thousands Separator: ` `	<--- non-breaking space (NBSP)
> INFO  - ColorsPlugin.Init - CurrentCulture: `pl-PL`
> INFO  - ColorsPlugin.Init - CurrentUICulture: pl-PL
> 
> 
> Slovak (Slovakia) Regional format (Failed ❌):
> 
> INFO  - ColorsPlugin.Init - Decimal Separator: ,
> INFO  - ColorsPlugin.Init - Thousands Separator: ` `	<--- non-breaking space (NBSP)
> INFO  - ColorsPlugin.Init - CurrentCulture: `sk-SK`
> INFO  - ColorsPlugin.Init - CurrentUICulture: pl-PL
> 
> 
> English (United States) Regional format (Works ✔️):
> 
> INFO  - ColorsPlugin.Init - Decimal Separator: `.`
> INFO  - ColorsPlugin.Init - Thousands Separator: `,`
> INFO  - ColorsPlugin.Init - CurrentCulture: `en-US`
> INFO  - ColorsPlugin.Init - CurrentUICulture: pl-PL
> 
> 
> German (Germany) Regional format (Failed ❌):
> 
> INFO  - ColorsPlugin.Init - Decimal Separator: `,`
> INFO  - ColorsPlugin.Init - Thousands Separator: `.`
> INFO  - ColorsPlugin.Init - CurrentCulture: `de-DE`
> INFO  - ColorsPlugin.Init - CurrentUICulture: pl-PL
> 
> 
> English (Germany) Regional format (Works ✔️):
> 
> INFO  - ColorsPlugin.Init - Decimal Separator: `,`
> INFO  - ColorsPlugin.Init - Thousands Separator: `.`
> INFO  - ColorsPlugin.Init - CurrentCulture: `en-DE`
> INFO  - ColorsPlugin.Init - CurrentUICulture: pl-PL
> 
> 
> Chinese (Simplified, China) Regional format (Works ✔️):
> 
> INFO  - ColorsPlugin.Init - Decimal Separator: `.`
> INFO  - ColorsPlugin.Init - Thousands Separator: `,`
> INFO  - ColorsPlugin.Init - CurrentCulture: `zh-CN`
> INFO  - ColorsPlugin.Init - CurrentUICulture: pl-PL
> 
> 
> Chinese (Simplified Han, Hong Kong SAR) (Failed ❌):
> 
> INFO  - ColorsPlugin.Init - Decimal Separator: `.`
> INFO  - ColorsPlugin.Init - Thousands Separator: `,`
> INFO  - ColorsPlugin.Init - CurrentCulture: `zh-Hans-HK`
> INFO  - ColorsPlugin.Init - CurrentUICulture: pl-PL

</details>

Turns out that `Regional Format` doesn't exactly need to be in English for this to work since `zh-CN` works properly, but at the same time `zh-Hans-HK` with identical separators fails with the same error as previously.

However, after some '_tinkering_' i managed to get it working with this:

``` diff

diff --git a/Main.cs b/Main.cs
index d840294..15524f5 100644
--- a/Main.cs
+++ b/Main.cs
@@ -155,10 +155,16 @@ private string CreateCacheImage(string name)
             using (var bitmap = new Bitmap(IMG_SIZE, IMG_SIZE))
             using (var graphics = Graphics.FromImage(bitmap))
             {
-                var color = ColorTranslator.FromHtml(name);
+                var colorCode = name;
+                var rgbRegex = new Regex(@"^(\d{1,3}),\s?(\d{1,3}),\s?(\d{1,3})$");
+                var isRgb = rgbRegex.IsMatch(colorCode);
+                if (isRgb)
+                {
+                    colorCode = RgbToHex(colorCode, rgbRegex); // Convert RGB to hex
+                }
+                var color = ColorTranslator.FromHtml(colorCode);
                 graphics.Clear(color);
 
                 var path = Path.Combine(ColorsDirectory.FullName, name+".png");
                 bitmap.Save(path, ImageFormat.Png);
                 return path;

```

And by tinkering i certainly don't mean failing scavenging the internet ( [[1]](https://stackoverflow.com/a/38697167) [[2]](http://referencesource.microsoft.com/#System.Drawing/commonui/System/Drawing/Advanced/ColorTranslator.cs,000c75cae51dfd2c) [[3]](https://stackoverflow.com/a/28692194) ) in search of anything that would make sense of this and ending up using ChatGPT, not at all, really… _Because technically it was Bing Chat Copilot, so that's completely different lol_. 

From what i've tested this works without any issues on my side no matter what `Regional Format` is selected.

Bonus check for RGB values above 255 because getting an error just from typing a higher value was really irritating:

``` Diff

diff --git a/Main.cs b/Main.cs
index 15524f5..0a216e3 100644
--- a/Main.cs
+++ b/Main.cs
@@ -71,6 +71,13 @@ public List<Result> Query(Query query)
                 if (!isRgb && !isHex)
                     return new List<Result>();
 
+                if (isRgb)
+                {
+                    var rgbValues = colorCode.Split(',').Select(int.Parse).ToList();
+                    if (rgbValues.Any(val => val > 255))
+                        return new List<Result>();
+                }
+
                 try
                 {
                     var createdColorImagePath = string.Empty;

```

Maybe this will give you any kind of insight why this is happening, or maybe the solution is good enough to incorporate it, but from my perspective this works good enough for me.

**Comment by MaskedRPGFan** [comment]
Thank you, @Sneakpeakcss, for this solution! It works great :) I created pull request with your changes. If someone wants to get this fix before it will be merged, just go to [this](https://github.com/MaskedRPGFan/Flow.Launcher.Plugin.Color) repo and get it from [releases](https://github.com/MaskedRPGFan/Flow.Launcher.Plugin.Color/releases).
